---
cache: pip

env:
  global:
    - DOCKER_COMPOSE_VERSION: 1.13.0

services:
  - docker

before_install:
  - sudo apt-get install shellcheck
  - sudo pip install yamllint
  - git clone https://github.com/IBM/pattern-ci

before_script:
  - "./pattern-ci/tests/shellcheck-lint.sh"
  - "./pattern-ci/tests/yaml-lint.sh"
  - "./scripts/setup-openwhisk.sh"

jobs:
  include:
    - script:
        - "./scripts/test-script.sh"
